from __future__ import annotations

import glob
import os
import tempfile

from music21 import metadata, stream


def apply_metadata(score: stream.Score, title: str) -> None:
    score.metadata = metadata.Metadata()
    score.metadata.title = title


def render_score_png_bytes(score: stream.Score) -> tuple[bytes | None, str | None]:
    try:
        with tempfile.TemporaryDirectory() as tmpdir:
            target = os.path.join(tmpdir, "score.png")
            score.write("musicxml.png", fp=target)
            files = glob.glob(os.path.join(tmpdir, "*.png"))
            if not files:
                return None, "PNG export failed: no image output generated by renderer."
            files.sort(key=os.path.getmtime, reverse=True)
            with open(files[0], "rb") as f:
                return f.read(), None
    except Exception as exc:
        return None, f"PNG export failed: {exc}"


def render_score_pdf_bytes(score: stream.Score) -> tuple[bytes | None, str | None]:
    try:
        with tempfile.TemporaryDirectory() as tmpdir:
            target = os.path.join(tmpdir, "score.pdf")
            out = score.write("musicxml.pdf", fp=target)
            if not out or not os.path.exists(out):
                return None, "PDF export failed: no PDF output generated by renderer."
            with open(out, "rb") as f:
                return f.read(), None
    except Exception as exc:
        return None, f"PDF export failed: {exc}"
